unbind C-b
set -g prefix 'M-s'
bind-key 'M-s' send-prefix
set -g default-terminal "tmux-256color"

set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on
set-option -g status-position top

bind-key  h select-pane -L
bind-key  j select-pane -D
bind-key  k select-pane -U

set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'catppuccin/tmux#v2.1.0'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tpm'

set-option -g set-titles on
set-option -g set-titles-string "#T"
bind '"' split-window -v -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"

set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_flags "icon"
set -g @catppuccin_window_flags_icon_zoom " "
set -g @catppuccin_window_flags_icon_current " "
set -g @catppuccin_window_flags_icon_last " "
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
# set -g status-left "#{E:@catppuccin_status_session}"
set -g status-left "#{E:@catppuccin_status_session}"
set -g status-right ""
set -ag status-right "#{E:@catppuccin_status_application}"
# set -agF status-left "#[fg=#{@thm_crust},bg=#{@thm_teal}] ##S █"
run -b '~/.config/tmux/plugins/tpm/tpm'

