set -g base-index 1
setw -g pane-base-index 1
set -g allow-passthrough on

unbind C-b
set -g prefix 'C-s'
bind-key 'C-s' send-prefix

unbind r
bind r source-file ~/.config/tmux/tmux.conf
set-option -g renumber-windows on
setw -g mode-keys vi
bind-key -r h select-pane -L
bind-key -r j select-pane -D
bind-key -r k select-pane -U
bind-key -r l select-pane -R

set-option -g status-position top

set-option -g set-titles on
set-option -g set-titles-string "#T"

bind '"' split-window -v -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"

set-option -g status-interval 1
# https://github.com/catppuccin/tmux/blob/main/README.md?plain=1
#Macchiato
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
run ~/.config/tmux/plugins/tmux/catppuccin.tmux
set -g status-left-length 200
set -g status-right-length 100
set -g status-right ""
set -g status-left ""
set -ag status-right "#{E:@catppuccin_status_application}"
set -ag status-left "#{E:@catppuccin_status_session}"
set -g @catppuccin_window_default_text "#{pane_title}"
set -g @catppuccin_window_current_text "#{pane_title}"
set -g @catppuccin_window_status_enable "yes"
set -g @catppuccin_window_status_icon_enable "yes"

set -gF window-status-format "#[bg=#{@ctp_surface_1},fg=#{@ctp_fg}] ##I ##T "
set -gF window-status-current-format "#[bg=#{@ctp_mauve},fg=#{@ctp_crust}] ##I ##T "
# set -gF window-status-format "#{?window_zoomed_flag,#[fg=red](,}#W#{?window_zoomed_flag,#[fg=red]),}"
# set -gF window-status-current-format "#{?window_zoomed_flag,#[fg=red](,}#W#{?window_zoomed_flag,#[fg=red]),}"
#======================= Plugins
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

run '~/.config/tmux/plugins/tpm/tpm'
