export EDITOR='nvim'
alias vim=nvim
alias cat=bat
export PATH=$PATH:/opt/homebrew/bin
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
export PATH="$HOME/.gem/ruby/3.3.0/bin:$PATH"

export KEYTIMEOUT=1

precmd() {
    cwd=${PWD##*/}
    cwd=${cwd:-/}
    eval 'printf "\033]2;${cwd}\007"'
}

ssh() {
    if [[ ! -z $TMUX ]]; then
        SERVER=$(command ssh -G $@ | grep ^hostname | awk '{print $2}')
        # printf "\033]2;󰌘 $SERVER\007"
        if [[ $SERVER =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            printf "\033]2;󰌘 ${SERVER}\007"
        else
            printf "\033]2;󰌘 ${SERVER%%.*}\007"
        fi    
    fi
    command ssh "$@"
}

##################### ctrl-w
#
# Create a new widget.
zle -N backward-kill-space-word
backward-kill-space-word() {
  # Inform the line editor that this widget will kill text.
  zle -f kill

  # Set $WORDCHARS for this command only. 
  WORDCHARS='*?_-.[]~=/&;!#$%^(){}<>|' zle .backward-kill-word
}

# See comments above.
zle -N backward-kill-bash-word
backward-kill-bash-word() {
  zle -f kill
  WORDCHARS='' zle .backward-kill-word
}

# Bind the widgets to keys.
bindkey   '^W' backward-kill-space-word
bindkey '^[^H' backward-kill-bash-word

export FZF_CTRL_T_OPTS=" 
  --walker-skip .git,node_modules,target
  --preview 'bat -n --color=always {}'
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"

export FZF_CTRL_R_OPTS=" 
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"
